# Example  .gitlab-ci.yml file
stages:
  - mavenbuild
  - maventest
  - mavenDeploy
  - androidbuild
  - androidtest

maven-build:   #this is a JOB
  stage: mavenbuild
  tags:
    - springboot  # this is LINK to the shell runner on the remote-server 
  script:
    - cd Backend
    - cd backend
    - mvn package -B

maven-test:
  stage: maventest
  tags:
    - springboot
  script:
    - cd Backend
    - cd backend
    - mvn test
  artifacts:
    paths:
      - Backend/backend/target/*.jar

# Below job builds, deploys, executes jar as service.
autoDeploy:
  stage: mavenDeploy  #do make a stage with same name!
  tags:
   - springboot
  script:
    - cd Backend
    - cd backend
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo

android-build: #this is another job
  image: gjandres/android-ci:latest      # this is a directive to DOCKER
  stage: androidbuild
  tags:
    - android      #this is LINK to the docker runner on the remote-server        
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/frontend/gradlew
  script:
    - cd Frontend
    - cd frontend
    - ./gradlew build
  artifacts:
    paths:
    - Android_test/app/build/outputs/
  when: manual

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/frontend/gradlew
  tags:
   - android
  script:
    - cd Frontend
    - cd frontend
    - ./gradlew test
  when: manual



